<?php
$pageTitle = "Create Quiz";
require_once __DIR__ . '/../includes/header.php';
requireTeacher();

$teacherId = (int)$_SESSION['user_id'];
$db = getDB();

// Fetch categories
$categories = $db->query("SELECT * FROM categories ORDER BY name ASC")->fetchAll();

// Pre-generate a unique Quiz ID to display to the teacher
$autoGeneratedQuizCode = generateUniqueQuizCode();

$error = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $title = trim($_POST['title'] ?? '');
    $description = trim($_POST['description'] ?? '');
    $categoryId = (int)($_POST['category_id'] ?? 0);
    $difficulty = trim($_POST['difficulty'] ?? 'Medium');
    $startDatetime = trim($_POST['start_datetime'] ?? '');
    $endDatetime = trim($_POST['end_datetime'] ?? '');
    $maxAttempts = max(1, (int)($_POST['max_attempts'] ?? 1));
    $status = in_array($_POST['status'] ?? '', ['published', 'draft']) ? $_POST['status'] : 'published';

    // Validation
    if (empty($title)) {
        $error = "Quiz title is required.";
    } elseif ($categoryId <= 0) {
        $error = "Please select a valid quiz category.";
    } elseif (empty($startDatetime) || empty($endDatetime)) {
        $error = "Both start and end dates/times are required.";
    } elseif (strtotime($endDatetime) <= strtotime($startDatetime)) {
        $error = "End date and time must be later than the start date and time.";
    } else {
        // Generate a guaranteed unique quiz code at insertion time
        $finalQuizCode = generateUniqueQuizCode();

        $stmt = $db->prepare("
            INSERT INTO quizzes (quiz_code, teacher_id, category_id, title, description, difficulty, start_datetime, end_datetime, max_attempts, status)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ");
        $stmt->execute([
            $finalQuizCode,
            $teacherId,
            $categoryId,
            $title,
            $description,
            $difficulty,
            $startDatetime,
            $endDatetime,
            $maxAttempts,
            $status
        ]);
        $newQuizId = (int)$db->lastInsertId();

        setFlash('success', "Quiz created successfully with Quiz ID: <strong>{$finalQuizCode}</strong>. Now add your MCQ questions!");
        header("Location: " . BASE_URL . "/teacher/manage_questions.php?quiz_id=" . $newQuizId);
        exit();
    }
}

// Default start and end dates (starts now, ends in 7 days)
$defaultStart = date('Y-m-d\TH:i');
$defaultEnd = date('Y-m-d\TH:i', strtotime('+7 days'));
?>

<div class="container py-4">
    <div class="row justify-content-center">
        <div class="col-lg-9">
            <div class="d-flex justify-content-between align-items-center mb-4">
                <div>
                    <h3 class="fw-bold text-white mb-1"><i class="fa-solid fa-plus-circle text-primary me-2"></i>Create New Quiz</h3>
                    <p class="text-secondary small mb-0">Set up quiz details. The system automatically creates a unique Quiz ID.</p>
                </div>
                <a href="<?= BASE_URL ?>/teacher/dashboard.php" class="btn btn-outline-secondary btn-sm rounded-pill px-3">
                    <i class="fa-solid fa-arrow-left me-1"></i> Dashboard
                </a>
            </div>

            <div class="arena-card p-4 p-md-5">
                <?php if (!empty($error)): ?>
                    <div class="alert alert-danger d-flex align-items-center bg-danger bg-opacity-25 border-danger text-danger-emphasis rounded-3 mb-4">
                        <i class="fa-solid fa-circle-exclamation fa-lg me-2 text-danger"></i>
                        <div><?= sanitize($error) ?></div>
                    </div>
                <?php endif; ?>

                <!-- Auto-Generated Quiz ID Notice -->
                <div class="p-3 rounded-3 bg-dark border border-secondary mb-4 d-flex flex-wrap justify-content-between align-items-center gap-2">
                    <div>
                        <div class="text-secondary small">Automatically Generated Quiz ID:</div>
                        <div class="quiz-code-badge fs-5 mt-1"><?= $autoGeneratedQuizCode ?></div>
                    </div>
                    <div class="small text-secondary">
                        <i class="fa-solid fa-circle-info text-info me-1"></i> Students will use this unique ID to identify & join the quiz.
                    </div>
                </div>

                <form action="<?= BASE_URL ?>/teacher/create_quiz.php" method="POST" id="quizForm" novalidate>
                    <div class="row g-3">
                        <div class="col-12">
                            <label for="title" class="form-label">Quiz Title <span class="text-danger">*</span></label>
                            <input type="text" class="form-control form-arena" id="title" name="title" required placeholder="e.g. Database Fundamentals" value="<?= isset($_POST['title']) ? sanitize($_POST['title']) : '' ?>">
                            <div class="invalid-feedback">Quiz title is required.</div>
                        </div>

                        <div class="col-12">
                            <label for="description" class="form-label">Quiz Description</label>
                            <textarea class="form-control form-arena" id="description" name="description" rows="3" placeholder="Provide context, instructions, or topics covered..."><?= isset($_POST['description']) ? sanitize($_POST['description']) : '' ?></textarea>
                        </div>

                        <div class="col-md-6">
                            <label for="category_id" class="form-label">Category <span class="text-danger">*</span></label>
                            <select class="form-select form-arena" id="category_id" name="category_id" required>
                                <option value="">Select Category...</option>
                                <?php foreach ($categories as $cat): ?>
                                    <option value="<?= $cat['id'] ?>" <?= (isset($_POST['category_id']) && (int)$_POST['category_id'] === (int)$cat['id']) ? 'selected' : '' ?>>
                                        <?= sanitize($cat['name']) ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                            <div class="invalid-feedback">Please select a category.</div>
                        </div>

                        <div class="col-md-6">
                            <label for="difficulty" class="form-label">Difficulty Level</label>
                            <select class="form-select form-arena" id="difficulty" name="difficulty">
                                <option value="Easy" <?= (isset($_POST['difficulty']) && $_POST['difficulty'] === 'Easy') ? 'selected' : '' ?>>Easy</option>
                                <option value="Medium" <?= (!isset($_POST['difficulty']) || $_POST['difficulty'] === 'Medium') ? 'selected' : '' ?>>Medium</option>
                                <option value="Hard" <?= (isset($_POST['difficulty']) && $_POST['difficulty'] === 'Hard') ? 'selected' : '' ?>>Hard</option>
                            </select>
                        </div>

                        <div class="col-md-6">
                            <label for="start_datetime" class="form-label">Start Date & Time <span class="text-danger">*</span></label>
                            <input type="datetime-local" class="form-control form-arena" id="start_datetime" name="start_datetime" required value="<?= isset($_POST['start_datetime']) ? sanitize($_POST['start_datetime']) : $defaultStart ?>">
                            <div class="invalid-feedback">Start date & time is required.</div>
                        </div>

                        <div class="col-md-6">
                            <label for="end_datetime" class="form-label">End Date & Time <span class="text-danger">*</span></label>
                            <input type="datetime-local" class="form-control form-arena" id="end_datetime" name="end_datetime" required value="<?= isset($_POST['end_datetime']) ? sanitize($_POST['end_datetime']) : $defaultEnd ?>">
                            <div class="invalid-feedback">End date & time must be after start time.</div>
                        </div>

                        <div class="col-md-6">
                            <label for="max_attempts" class="form-label">Maximum Attempts per Student</label>
                            <input type="number" class="form-control form-arena" id="max_attempts" name="max_attempts" min="1" max="10" value="<?= isset($_POST['max_attempts']) ? (int)$_POST['max_attempts'] : 1 ?>">
                            <div class="form-text text-secondary">Set to 1 for strict one-time assessments.</div>
                        </div>

                        <div class="col-md-6">
                            <label for="status" class="form-label">Publishing Status</label>
                            <select class="form-select form-arena" id="status" name="status">
                                <option value="published" <?= (!isset($_POST['status']) || $_POST['status'] === 'published') ? 'selected' : '' ?>>Published (Visible to students)</option>
                                <option value="draft" <?= (isset($_POST['status']) && $_POST['status'] === 'draft') ? 'selected' : '' ?>>Draft (Hidden until published)</option>
                            </select>
                        </div>

                        <div class="col-12 mt-4 pt-2 border-top border-secondary">
                            <button type="submit" class="btn btn-arena-primary w-100 py-2 fs-6">
                                <i class="fa-solid fa-arrow-right me-2"></i>Save & Proceed to Add Questions
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<?php require_once __DIR__ . '/../includes/footer.php'; ?>
