<?php
require_once __DIR__ . '/../config/database.php';
require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../includes/functions.php';
requireTeacher();

$teacherId = (int)$_SESSION['user_id'];
$db = getDB();

// Fetch categories
$categories = $db->query("SELECT * FROM categories ORDER BY name ASC")->fetchAll();

// Pre-generate a unique Quiz ID to display to the teacher
$autoGeneratedQuizCode = generateUniqueQuizCode();

$error = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $title = trim($_POST['title'] ?? '');
    $description = trim($_POST['description'] ?? '');

    // Validation
    if (empty($title)) {
        $error = "Quiz title is required.";
    } else {
        // Fetch default category ID if available
        $defaultCatStmt = $db->query("SELECT id FROM categories ORDER BY id ASC LIMIT 1");
        $defaultCat = $defaultCatStmt->fetch();
        $categoryId = $defaultCat ? (int)$defaultCat['id'] : 1;

        // Default initial schedule and settings (Teacher defines Date, Time & Done in Step 2/3)
        $difficulty = 'Medium';
        $startDatetime = date('Y-m-d H:i:s');
        $endDatetime = date('Y-m-d H:i:s', strtotime('+7 days'));
        $maxAttempts = 1;
        $status = 'published';

        // Generate a guaranteed unique quiz code at insertion time
        $finalQuizCode = generateUniqueQuizCode();

        $stmt = $db->prepare("
            INSERT INTO quizzes (quiz_code, teacher_id, category_id, title, description, difficulty, start_datetime, end_datetime, max_attempts, status)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ");
        $stmt->execute([
            $finalQuizCode,
            $teacherId,
            $categoryId,
            $title,
            $description,
            $difficulty,
            $startDatetime,
            $endDatetime,
            $maxAttempts,
            $status
        ]);
        $newQuizId = (int)$db->lastInsertId();

        setFlash('success', "Quiz \"<strong>" . htmlspecialchars($title) . "</strong>\" created with Quiz ID <strong>{$finalQuizCode}</strong>. Now set your questions and answers!");
        header("Location: " . BASE_URL . "/teacher/manage_questions.php?quiz_id=" . $newQuizId);
        exit();
    }
}

$pageTitle = "Create Quiz";
require_once __DIR__ . '/../includes/header.php';

// Default start and end dates (starts now, ends in 7 days)
$defaultStart = date('Y-m-d\TH:i');
$defaultEnd = date('Y-m-d\TH:i', strtotime('+7 days'));
?>

<div class="container py-4">
    <div class="row justify-content-center">
        <div class="col-lg-9">
            <div class="d-flex justify-content-between align-items-center mb-4">
                <div>
                    <h3 class="fw-bold text-white mb-1"><i class="fa-solid fa-plus-circle text-primary me-2"></i>Create New Quiz</h3>
                    <p class="text-secondary small mb-0">Set up quiz details. The system automatically creates a unique Quiz ID.</p>
                </div>
                <a href="<?= BASE_URL ?>/teacher/dashboard.php" class="btn btn-outline-secondary btn-sm rounded-pill px-3">
                    <i class="fa-solid fa-arrow-left me-1"></i> Dashboard
                </a>
            </div>

            <div class="arena-card p-4 p-md-5">
                <?php if (!empty($error)): ?>
                    <div class="alert alert-danger d-flex align-items-center bg-danger bg-opacity-25 border-danger text-danger-emphasis rounded-3 mb-4">
                        <i class="fa-solid fa-circle-exclamation fa-lg me-2 text-danger"></i>
                        <div><?= sanitize($error) ?></div>
                    </div>
                <?php endif; ?>

                <!-- Auto-Generated Quiz ID Notice -->
                <div class="p-3 rounded-3 bg-dark border border-secondary mb-4 d-flex flex-wrap justify-content-between align-items-center gap-2">
                    <div>
                        <div class="text-secondary small">Automatically Generated Quiz ID:</div>
                        <div class="quiz-code-badge fs-5 mt-1"><?= $autoGeneratedQuizCode ?></div>
                    </div>
                    <div class="small text-secondary">
                        <i class="fa-solid fa-circle-info text-info me-1"></i> Students will use this unique ID to identify & join the quiz.
                    </div>
                </div>

                <!-- Workflow Guide Indicator -->
                <div class="p-3 rounded-3 bg-dark border border-secondary mb-4">
                    <div class="d-flex flex-wrap align-items-center gap-2">
                        <span class="badge bg-primary rounded-pill px-3 py-2 fw-semibold">
                            <i class="fa-solid fa-1 me-1"></i> Step 1: Basic Quiz Info
                        </span>
                        <i class="fa-solid fa-arrow-right text-secondary fa-xs"></i>
                        <span class="badge bg-secondary text-light rounded-pill px-3 py-2 fw-normal">
                            <i class="fa-solid fa-2 me-1"></i> Step 2: Set Questions &amp; Answers
                        </span>
                        <i class="fa-solid fa-arrow-right text-secondary fa-xs"></i>
                        <span class="badge bg-secondary text-light rounded-pill px-3 py-2 fw-normal">
                            <i class="fa-solid fa-3 me-1"></i> Step 3: Define Date, Time &amp; Done
                        </span>
                    </div>
                </div>

                <form action="<?= BASE_URL ?>/teacher/create_quiz.php" method="POST" id="quizForm" novalidate>
                    <div class="row g-4">
                        <div class="col-12">
                            <label for="title" class="form-label fw-semibold">Quiz Title <span class="text-danger">*</span></label>
                            <input type="text" class="form-control form-arena fs-5 py-2" id="title" name="title" required placeholder="e.g. Database Fundamentals & SQL Mastery" value="<?= isset($_POST['title']) ? sanitize($_POST['title']) : '' ?>">
                            <div class="invalid-feedback">Quiz title is required.</div>
                        </div>

                        <div class="col-12">
                            <label for="description" class="form-label fw-semibold">Quiz Description <span class="text-secondary small fw-normal">(Optional)</span></label>
                            <textarea class="form-control form-arena" id="description" name="description" rows="4" placeholder="Provide overview, instructions, or topics covered for your students..."><?= isset($_POST['description']) ? sanitize($_POST['description']) : '' ?></textarea>
                            <div class="form-text text-secondary">
                                <i class="fa-solid fa-lightbulb text-warning me-1"></i> You will set up questions &amp; answers next. Date, time, and scheduling are defined right before completing the quiz.
                            </div>
                        </div>

                        <div class="col-12 mt-4 pt-2 border-top border-secondary">
                            <button type="submit" class="btn btn-arena-primary w-100 py-3 fs-6 fw-bold">
                                <i class="fa-solid fa-arrow-right me-2"></i>Create Quiz &amp; Continue to Set Questions
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<?php require_once __DIR__ . '/../includes/footer.php'; ?>
